Add Harcoded secrets in kubernetes secrets
di-unipi-socc/kube-hound pull request #3
Opened 2023-04-11 15:56 UTC by DCreati

2023-04-11 17:58 UTC, gio54321 requested changes
Mi sembra un ottimo lavoro! Ho giusto un paio di commenti che dovrebbero essere semplici da implementare.

Bisogna fare il commit dei file `poetry.lock` e `pyproject.toml`, altrimenti non si riesce ad avere un environment riproducibile. Di fatto non sono riuscito a eseguire il codice localmente perché la dipendenza di `checkov` e la versione di Python richiesta dal codice (>3.10 per usare il costrutto `match`) non sono specificati nei file di configurazione attuali di Poetry (see also https://python-poetry.org/docs/basic-usage/#commit-your-poetrylock-file-to-version-control)

Per questa analisi non creerei un nuovo smell in `smells.py`, ma semplicemente ritornerei lo smell Hardcoded Secrets `HS` già presente nella enumerazione, così il mapping dei security smell resta consistente.

Minor: aggiungerei un file `README.md` dentro `data/examples/secrets_kubernetes` che descrive il test, per essere consistente con le altre analisi (per esempio https://github.com/di-unipi-socc/kube-hound/blob/master/data/examples/pod_to_pod_traffic/README.md)

2023-04-12 10:17 UTC, DCreati commented
Aggiunte le correzioni necessarie

2023-04-12 10:20 UTC, DCreati commented
Aggiunto/Corretto le modifiche richieste

2023-04-12 14:07 UTC, gio54321 commented
Ottimo grazie, sono un attimo impazzito perché non riuscivo a riprodurre l'output, ma a quanto pare Bridgecrew mantiene un suo fork di `detect-secrets` (https://pypi.org/project/bc-detect-secrets/) ed è questo che viene usato da Checkov, mentre per un'altra analisi usavamo già `detect-secrets`.
A quanto pare le due versioni hanno lo stesso nome del modulo Python, il che rende il tutto abbastanza confuso :raised_eyebrow:

Per risolvere dovrebbe bastare rimuovere la dipendenza di `detect-secrets` da `pyproject.toml`
```
GitPython = "^3.1.27"
loguru = "^0.6.0"
kubernetes = "^24.2.0"
detect-secrets = "^1.4.0"    <----
docker = "^6.0.0"
pyshark = "^0.5.3"
```
e le dipendenze dovrebbero risultare corrette. Se puoi implementare questa ultima cosa (rigenerando un nuovo `poetry.lock`) sarebbe perfetto.
In ogni caso con le nuove dipendenze sono riuscito a riprodurre l'output, che mi sembra corretto :slightly_smiling_face:

2023-04-12 14:45 UTC, DCreati commented
Ho provato a rimuovere la dipendenza e aggiornato anche il `poetry.lock`. Però facendo cosi a me non trova più la libreria:

```
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code

....
....

from detect_secrets import SecretsCollection
ImportError: cannot import name 'SecretsCollection' from 'detect_secrets' (unknown location)
```

Mentre tenendo tutto come ho caricato non mi crea problemi.

2023-04-12 16:39 UTC, gio54321 commented
Ok è molto strano, ma ho creato un `Dockerfile` al volo per vedere come si comporta su un environment nuovo, e effettivamente senza la dipendenza `detect-secrets` funziona, mentre con la dipendenza non funziona, restituendo in output
```
WARNING:root:Secret scanning: could not process file /usr/src/app/data/examples/secrets_kubernetes/secret.yaml
```
Presumo che poetry faccia confusione con due moduli diversi che hanno lo stesso nome (che sono abbastanza sicuro che non dovrebbe accadere), io ho risolto eliminando la cache dei virtual env di Poetry (nel mio sistema è in `~/.cache/pypoetry`). Ma non ne sono troppo sicuro.

---

Dockerfile:
```dockerfile
FROM python:3.11

WORKDIR /usr/src/app

COPY . .

# install poetry
RUN curl -sSL https://install.python-poetry.org | python -

# add "/root/.local/bin" to PATH
ENV PATH="/root/.local/bin:${PATH}"

# install dependencies
RUN poetry install

# run the app
CMD ["poetry", "run", "python", "-m", "kube_hound"]
```

Steps to reproduce:
```sh
poetry lock
docker build -t kube-hound .
docker run --rm -it --entrypoint data/examples/secrets_kubernetes/run.sh -t kube-hound
```

---

PS: dovremmo effettivamente considerare di aggiungere un `Dockerfile` al progetto (anche partendo da questo) per avere build/test riproducibili.

2023-04-13 07:36 UTC, DCreati commented
Ho provato a controllare anche io "resettando" poetry. Effettivamente con la dipendenza inclusa nel `pyproject.toml` generava errore.
Grazie per la dritta.
Ho caricato i nuovi file di poetry senza la dipendenza.

2023-04-14 09:26 UTC, gio54321 approved these changes
LGTM, aspetto una review di @jsoldani poi possiamo fare merge

2023-04-14 15:47 UTC, jsoldani commented
LGTM. Procedo con il merge :-)

2023-04-14 15:47 UTC, merged