Hardcoded secrets in Docker and Source code
di-unipi-socc/kube-hound pull request #5
Opened 2023-04-26 12:29 UTC by DCreati

2023-05-02 06:36 UTC, gio54321 reviewed
Looks very good, thanks!

I would add a couple more test cases to the already existing ones, like one or more environment variables in the Dockerfile containing secrets (like database passwords or API keys) and some more examples of secrets in source code, maybe even in different programming languages, to further assess the efficacy of the plugin.

Other than that, for me it looks good and we can then merge it.

2023-05-02 15:44 UTC, DCreati commented
Dall'ultimo push ho corretto l'analizzazione del sourcecode. Io avevo inteso che funzionasse come ad esempio la lista che contiene i file di kubernetes: che ritorna una lista di application object ognugno associato al singolo file. Mentre per sourcecode ritorna un singolo ApplicationObject con il path della cartella o del file.
Ho inserito "brutalmente" all'interno dell'analisi il parsing del sourcecode in modo da leggere eventuali file nella root o sotto cartelle. Onestamente non credo sia una buona pratica mischiare all'analisi questa funzionalità, ma piuttosto adattare il parsing stesso.
Aspetto risposte sull'operato.

2023-05-03 09:50 UTC, DCreati commented
Ho notato adesso che c'è una sovrapposizione del dockerfile, che viene letto anche dal sourcecode quindi il risultato dell'analisi viene stampato due volte. Procedo con la correzzione e il commit

2023-05-11 08:48 UTC, DCreati commented
Come prima cosa è dato per scontato che i file di `kubernetes`, `docker` e `sourcecode` non si trovino all'interno della cartella segnalata in `sourcecode`. Se cosi non fosse `sourcecode` includerà anche i primi due, **si potrebbe avere una doppia stampa di uno smell di docker** e **anche l'inclusione dei file di kubernetes** (Compito di un'altra analisi). 

Per il sourcecode l'analisi è estesa a tutti i file contenuti nella cartella (ricorsivamente).

2023-05-17 20:43 UTC, gio54321 requested changes
Ho testato il codice e mi pare funzioni correttamente, grazie per le modifiche! Ci sono un paio di cose che secondo me potrebbero essere migliorate.

Per prima cosa cercherei di risolvere il più possibile gli errori dati da `mypy` e `flake8`. Questi tool si possono eseguire con
```sh
./scripts/typecheck_and_lint.sh
```
Chiaramente non è necessario risolvere tutti gli errori, ma possono dare segnali utili. Per esempio segnalano che a linea 29 di `hardcoded_docker_source_secrets.py` la variabile `result` non è definita.

Per i file di test che contengono i segreti, li metterei dentro una sotto cartella `src` dentro `data/examples/secrets_in_docker_source` così secondo me può risultare più pulita la struttura della repository.

Infine, forse sarebbe meglio rinominare i Dockerfiles con la naming convention [riportata anche nella documentazione ufficiale](https://docs.docker.com/engine/reference/commandline/build/#file) che sarebbe `Dockerfile.<descrizione>`. Così si può riuscire facilmente a distinguere i Dockerfile da file generici.

2023-05-18 08:13 UTC, DCreati commented
Ringrazio per la revisione. Già che c'ero ho corretto anche alcune imprecisioni sintattiche dell'analisi sui kubernetes secrets.

Per la rinomina del dockerfile ho controllato anche la seguente domanda su [Stackoverflow](https://stackoverflow.com/questions/26077543/how-to-name-dockerfiles#answer-51205428)

2023-06-15 08:24 UTC, jsoldani commented
@gio54321 can you please check the implementation of the requested changes? :-)

2023-06-15 10:49 UTC, gio54321 commented
Sorry for the delay.

Looks good to me, the code and structure of the files are much better than the previous review iteration, and the analysis seems to work well. I have tested also on Sock Shop and it found a bunch of hardcoded credentials, with seemingly no false positives:

<details>
  <summary>Sock Shop output</summary>

```
Hardcoded docker and source secrets analysis - detected smells {HS}
	Description: Base64 High Entropy String
	File: /apispec/hooks.js:13-14 
	Error(s): 
	-- 13 |	    "password": "tes*********"
	

Hardcoded docker and source secrets analysis - detected smells {HS}
	Description: Basic Auth Credentials
	File: /db/mongodb/mongodb_test.go:153-154 
	Error(s): 
	-- 153 |	if u.String() != "mongodb://test:pa******@thishostshouldnotexist:3038/users" {
	

Hardcoded docker and source secrets analysis - detected smells {HS}
	Description: Base64 High Entropy String
	File: /docker/user-db/scripts/customer-insert.js:14-15 
	Error(s): 
	-- 14 |    "password": "fec51a**********************************",
	

Hardcoded docker and source secrets analysis - detected smells {HS}
	Description: Base64 High Entropy String
	File: /docker/user-db/scripts/customer-insert.js:25-26 
	Error(s): 
	-- 25 |    "password": "e2de72**********************************",
	

Hardcoded docker and source secrets analysis - detected smells {HS}
	Description: Base64 High Entropy String
	File: /docker/user-db/scripts/customer-insert.js:36-37 
	Error(s): 
	-- 36 |    "password": "8f31df**********************************",
```

</details>

So we can merge on my end, thanks for the patience :sweat_smile:

2023-06-15 10:49 UTC, gio54321 approved these changes

2023-06-15 10:54 UTC, jsoldani commented
Thank you for checking, @gio54321. I will hence merge the pull request :-)

2023-06-15 10:54 UTC, merged